# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          "Shivam Pandey"
paginate:       5
baseurl:        ""
url:            "https://pandeyiyer.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Shivam Pandey
  url:          https://pandeyiyer.github.io
  email:        pandeyiyer@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
